"""added seller id column

Revision ID: 6428645a0daa
Revises: d48a28825de9
Create Date: 2022-06-10 10:46:31.768830

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6428645a0daa'
down_revision = 'd48a28825de9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gem', 'user', ['seller_id'], ['id'])
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_constraint(None, 'gem', type_='foreignkey')
    op.drop_column('gem', 'seller_id')
    # ### end Alembic commands ###
